unit TestTest1GUI;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Vcl.StdCtrls, Winapi.Windows,
  System.Variants, Vcl.Dialogs, Vcl.Controls, Test1GUI, Vcl.Forms, Winapi.Messages,
  System.Classes;

type
  // Test methods for class TForm1

  TestTForm1 = class(TTestCase)
  strict private
    FForm1: TForm1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestButton1Click;
    procedure TestCalcularSoma;
    procedure TestButton2Click;
  end;

implementation

procedure TestTForm1.SetUp;
begin
  FForm1 := TForm1.Create(nil);
end;

procedure TestTForm1.TearDown;
begin
  FForm1.Free;
  FForm1 := nil;
end;

procedure TestTForm1.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm1.Edit1.Text := '5';
  FForm1.Edit2.Text := '3';
  FForm1.Button1Click(Sender);

  // TODO: Validate method results
  CheckEquals('8', FForm1.Edit3.Text);
end;

procedure TestTForm1.TestCalcularSoma;
var
  ReturnValue: string;
  Value2: string;
  Value1: string;
begin
  // TODO: Setup method call parameters
  ReturnValue := FForm1.CalcularSoma('5', '5');
  // TODO: Validate method results
  CheckEquals('10', ReturnValue);
end;

procedure TestTForm1.TestButton2Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm1.Button2Click(Sender);
  // TODO: Validate method results
  CheckEquals('', FForm1.Edit1.Text);
  CheckEquals('', FForm1.Edit2.Text);
  CheckEquals('', FForm1.Edit3.Text);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTForm1.Suite);
end.

